### PR TITLE
Sometimes percentFuel return 0

### PR DESCRIPTION
**Pull request by RyuIce**
Sometimes percentFuel return 0, wich doesn't make sense with the displayed text.

### CODE REVIEW

**Comment by 7yl4r** [comment]
You're right that the text doesn't work for 0 fuel, but I don't think this is the right solution. 

Maybe we can have the text change based on the amount of fuel instead? (see [debrisEncounter.getHarvestText](https://github.com/7yl4r/the-oregon-trajectory/blob/master/ng-modules/debrisEncounter/debrisEncounter.coffee#L80-L88))

**Comment by RyuIce** [comment]
Why is it written as a TODO commentary instead of the code itself? Is it because you don't want to mess with the code without something better instead of "Nothing of use here." and "Something..."?

**Comment by 7yl4r** [comment]
That's exactly right! That's just filler text. We've got quite a but of that 'round these parts.

**Comment by 7yl4r** [comment]
Thanks again for highlighting this issue. Hopefully that fix I just pushed improves things.

**Pull request closed without merging**
