### PR TITLE
Fix issue #120

### PR DESCRIPTION
**Pull request by thegluestickman**
This should fix the spacemen being drawn over the text.

The z-index controls the stack order of the elements, I've set this to
ten to ensure that it is the top element. Cheers.

### CODE REVIEW

**Comment by thegluestickman** [comment]
This particular solution doesn't look like that would work. I'll fix it and reopen it then. Sorry about that.

**Comment by 7yl4r** [comment]
Does that fix not work? Looks good in theory, but I'm no css pro.

**Comment by thegluestickman** [comment]
I don't think it would have worked because the HTML needed some tweaking. I'm pretty sure z-indexing only applies to div tags. I changed the li tag to a p tag (unless it was supposed to be actually part of a bigger list?) and wrapped it in a div, the div tag now has the class game-over-text.

I will update it in my branch, but my linux distro is a bit buggered at the moment so I can't test it (using windows right now). _Theoretically_, it should work; practically, I don't know...

**Comment by 7yl4r** [comment]
Alright, I'll watch and give it a test when it's ready.

**Pull request closed without merging**
